### ISSUE TITLE
INFOGRAFIA_REALIDAD AUMENADA

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/infografia-EDITH-R#1]
![EDITH REYES SANCHEZ](https://user-images.githubusercontent.com/72045371/153771841-b7c30363-2c8f-478f-a5e2-ef934848f2ba.png)

**Comment by Christopherg2** [comment]
Muy bien compañera tu trabajo esta completo, y cumple con todos los requisitos. 
20 puntos

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado
