### ISSUE TITLE
Infografia_INGENIERIA DE REQUISITOS

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/infografia-EDITH-R#2]
[EDITH REYES_INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-EDITH-R/files/6104572/EDITH.REYES_INFOGRAFIA.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
